package com.inventory.demo.product.service;

import com.inventory.demo.exception.BusinessRuleException;
import com.inventory.demo.exception.ResourceNotFoundException;
import com.inventory.demo.product.api.CreateProductRequest;
import com.inventory.demo.product.api.PagedProductResponse;
import com.inventory.demo.product.api.ProductOptionRequest;
import com.inventory.demo.product.api.ProductResponse;
import com.inventory.demo.product.api.UpdateProductRequest;
import com.inventory.demo.product.domain.Product;
import com.inventory.demo.product.domain.ProductOption;
import com.inventory.demo.product.repository.ProductRepository;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class ProductServiceTest {

    @Mock
    private ProductRepository productRepository;

    @InjectMocks
    private ProductService productService;

    private static CreateProductRequest minimalRequest(String title) {
        return new CreateProductRequest(title, null, null, null, null,
                null, null, null, null, null, null, null);
    }

    private static CreateProductRequest requestWithHandle(String title, String handle) {
        return new CreateProductRequest(title, handle, null, null, null,
                null, null, null, null, null, null, null);
    }

    private static CreateProductRequest requestWithStatus(String title, String status) {
        return new CreateProductRequest(title, null, status, null, null,
                null, null, null, null, null, null, null);
    }

    private static CreateProductRequest fullRequest() {
        return new CreateProductRequest(
                "Premium Widget",
                "premium-widget",
                "PUBLISHED",
                "A premium widget description",
                "The best widget",
                new BigDecimal("1.5"),
                new BigDecimal("10.0"),
                new BigDecimal("5.0"),
                new BigDecimal("3.0"),
                "{\"color\":\"red\"}",
                "EXT-001",
                null
        );
    }

    @Nested
    class SuccessCases {

        @Test
        void shouldCreateProductWithAutoGeneratedHandle() {
            // given
            CreateProductRequest request = minimalRequest("My Cool Product");
            when(productRepository.existsByHandle("my-cool-product")).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.title()).isEqualTo("My Cool Product");
            assertThat(response.handle()).isEqualTo("my-cool-product");
            assertThat(response.status()).isEqualTo("DRAFT");
        }

        @Test
        void shouldCreateProductWithExplicitHandle() {
            // given
            CreateProductRequest request = requestWithHandle("My Product", "custom-handle");
            when(productRepository.existsByHandle("custom-handle")).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.handle()).isEqualTo("custom-handle");
        }

        @Test
        void shouldDefaultToDraftStatus() {
            // given
            CreateProductRequest request = minimalRequest("Test Product");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.status()).isEqualTo("DRAFT");
        }

        @Test
        void shouldApplyExplicitStatus() {
            // given
            CreateProductRequest request = requestWithStatus("Test Product", "PUBLISHED");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.status()).isEqualTo("PUBLISHED");
        }

        @Test
        void shouldApplyAllOptionalFields() {
            // given
            CreateProductRequest request = fullRequest();
            when(productRepository.existsByHandle("premium-widget")).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.title()).isEqualTo("Premium Widget");
            assertThat(response.handle()).isEqualTo("premium-widget");
            assertThat(response.status()).isEqualTo("PUBLISHED");
            assertThat(response.description()).isEqualTo("A premium widget description");
            assertThat(response.subtitle()).isEqualTo("The best widget");
            assertThat(response.weight()).isEqualByComparingTo(new BigDecimal("1.5"));
            assertThat(response.height()).isEqualByComparingTo(new BigDecimal("10.0"));
            assertThat(response.width()).isEqualByComparingTo(new BigDecimal("5.0"));
            assertThat(response.length()).isEqualByComparingTo(new BigDecimal("3.0"));
            assertThat(response.metadata()).isEqualTo("{\"color\":\"red\"}");
            assertThat(response.externalId()).isEqualTo("EXT-001");
        }

        @Test
        void shouldSaveProductToRepository() {
            // given
            CreateProductRequest request = minimalRequest("Save Test");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            productService.createProduct(request);

            // then
            ArgumentCaptor<Product> captor = ArgumentCaptor.forClass(Product.class);
            verify(productRepository).save(captor.capture());
            assertThat(captor.getValue().getTitle()).isEqualTo("Save Test");
        }

        @Test
        void shouldHandleCaseInsensitiveStatusInput() {
            // given
            CreateProductRequest request = requestWithStatus("Test Product", "published");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.status()).isEqualTo("PUBLISHED");
        }
    }

    @Nested
    class FailureCases {

        @Test
        void shouldRejectDuplicateHandle() {
            // given
            CreateProductRequest request = requestWithHandle("My Product", "existing-handle");
            when(productRepository.existsByHandle("existing-handle")).thenReturn(true);

            // when / then
            assertThatThrownBy(() -> productService.createProduct(request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("existing-handle")
                    .hasMessageContaining("already exists");

            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectDuplicateAutoGeneratedHandle() {
            // given
            CreateProductRequest request = minimalRequest("Existing Product");
            when(productRepository.existsByHandle("existing-product")).thenReturn(true);

            // when / then
            assertThatThrownBy(() -> productService.createProduct(request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("existing-product");

            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectInvalidStatus() {
            // given
            CreateProductRequest request = requestWithStatus("Test Product", "INVALID_STATUS");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);

            // when / then
            assertThatThrownBy(() -> productService.createProduct(request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("Invalid product status")
                    .hasMessageContaining("INVALID_STATUS");

            verify(productRepository, never()).save(any());
        }
    }

    @Nested
    class SlugGenerationCases {

        @Test
        void shouldConvertTitleToLowercaseSlug() {
            assertThat(productService.generateSlug("My Cool Product"))
                    .isEqualTo("my-cool-product");
        }

        @Test
        void shouldReplaceSpecialCharacters() {
            assertThat(productService.generateSlug("Product @ 50% Off!"))
                    .isEqualTo("product-50-off");
        }

        @Test
        void shouldCollapseConsecutiveHyphens() {
            assertThat(productService.generateSlug("Product -- Extra"))
                    .isEqualTo("product-extra");
        }

        @Test
        void shouldTrimLeadingAndTrailingHyphens() {
            assertThat(productService.generateSlug(" --Product-- "))
                    .isEqualTo("product");
        }

        @Test
        void shouldHandleMultipleSpaces() {
            assertThat(productService.generateSlug("Product   With   Spaces"))
                    .isEqualTo("product-with-spaces");
        }
    }

    @Nested
    class GetProductByIdCases {

        @Test
        void shouldReturnProductWhenFound() {
            // given
            Product product = Product.create("Existing Product", "existing-product");
            UUID productId = product.getId();
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));

            // when
            ProductResponse response = productService.getProductById(productId);

            // then
            assertThat(response.title()).isEqualTo("Existing Product");
            assertThat(response.handle()).isEqualTo("existing-product");
            assertThat(response.status()).isEqualTo("DRAFT");
        }

        @Test
        void shouldThrowNotFoundWhenProductDoesNotExist() {
            // given
            UUID unknownId = UUID.randomUUID();
            when(productRepository.findById(unknownId)).thenReturn(Optional.empty());

            // when / then
            assertThatThrownBy(() -> productService.getProductById(unknownId))
                    .isInstanceOf(ResourceNotFoundException.class)
                    .hasMessageContaining("Product")
                    .hasMessageContaining(unknownId.toString());
        }
    }

    @Nested
    class ListProductsCases {

        @Test
        void shouldReturnPagedProducts_whenNoFilter() {
            // given
            Product product = Product.create("Test Product", "test-product");
            Page<Product> page = new PageImpl<>(List.of(product), PageRequest.of(0, 20, Sort.by(Sort.Direction.DESC, "createdAt")), 1);
            when(productRepository.findAll(any(Specification.class), any(Pageable.class)))
                    .thenReturn(page);

            // when
            PagedProductResponse response = productService.listProducts(null, PageRequest.of(0, 20));

            // then
            assertThat(response.content()).hasSize(1);
            assertThat(response.content().getFirst().title()).isEqualTo("Test Product");
            assertThat(response.page()).isZero();
            assertThat(response.totalElements()).isEqualTo(1);
            assertThat(response.totalPages()).isEqualTo(1);
        }

        @Test
        void shouldReturnEmptyPage_whenNoProducts() {
            // given
            Page<Product> emptyPage = new PageImpl<>(List.of(), PageRequest.of(0, 20, Sort.by(Sort.Direction.DESC, "createdAt")), 0);
            when(productRepository.findAll(any(Specification.class), any(Pageable.class)))
                    .thenReturn(emptyPage);

            // when
            PagedProductResponse response = productService.listProducts(null, PageRequest.of(0, 20));

            // then
            assertThat(response.content()).isEmpty();
            assertThat(response.totalElements()).isZero();
            assertThat(response.totalPages()).isZero();
        }

        @Test
        void shouldFilterByStatus_whenStatusProvided() {
            // given
            Product publishedProduct = Product.create("Published Product", "published-product");
            Page<Product> page = new PageImpl<>(List.of(publishedProduct), PageRequest.of(0, 20, Sort.by(Sort.Direction.DESC, "createdAt")), 1);
            when(productRepository.findAll(any(Specification.class), any(Pageable.class)))
                    .thenReturn(page);

            // when
            PagedProductResponse response = productService.listProducts("PUBLISHED", PageRequest.of(0, 20));

            // then
            assertThat(response.content()).hasSize(1);
            verify(productRepository).findAll(any(Specification.class), any(Pageable.class));
        }

        @Test
        void shouldHandleCaseInsensitiveStatusFilter() {
            // given
            Page<Product> page = new PageImpl<>(List.of(), PageRequest.of(0, 20, Sort.by(Sort.Direction.DESC, "createdAt")), 0);
            when(productRepository.findAll(any(Specification.class), any(Pageable.class)))
                    .thenReturn(page);

            // when
            PagedProductResponse response = productService.listProducts("published", PageRequest.of(0, 20));

            // then
            assertThat(response).isNotNull();
            verify(productRepository).findAll(any(Specification.class), any(Pageable.class));
        }

        @Test
        void shouldThrowBusinessRuleException_whenInvalidStatus() {
            // when / then
            assertThatThrownBy(() -> productService.listProducts("INVALID", PageRequest.of(0, 20)))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("Invalid product status")
                    .hasMessageContaining("INVALID");

            verify(productRepository, never()).findAll(any(Specification.class), any(Pageable.class));
        }

        @Test
        @SuppressWarnings("PMD.JUnitTestContainsTooManyAsserts")
        void shouldCapPageSizeToMaximum() {
            // given
            Page<Product> page = new PageImpl<>(List.of(), PageRequest.of(0, 100, Sort.by(Sort.Direction.DESC, "createdAt")), 0);
            when(productRepository.findAll(any(Specification.class), any(Pageable.class)))
                    .thenReturn(page);

            // when
            productService.listProducts(null, PageRequest.of(0, 200));

            // then
            @SuppressWarnings("unchecked")
            ArgumentCaptor<Pageable> pageableCaptor = ArgumentCaptor.forClass(Pageable.class);
            verify(productRepository).findAll(any(Specification.class), pageableCaptor.capture());
            assertThat(pageableCaptor.getValue().getPageSize()).isEqualTo(100);
        }

        @Test
        @SuppressWarnings("PMD.JUnitTestContainsTooManyAsserts")
        void shouldApplyDefaultSortWhenUnsorted() {
            // given
            Page<Product> page = new PageImpl<>(List.of(), PageRequest.of(0, 20, Sort.by(Sort.Direction.DESC, "createdAt")), 0);
            when(productRepository.findAll(any(Specification.class), any(Pageable.class)))
                    .thenReturn(page);

            // when
            productService.listProducts(null, PageRequest.of(0, 20));

            // then
            @SuppressWarnings("unchecked")
            ArgumentCaptor<Pageable> pageableCaptor = ArgumentCaptor.forClass(Pageable.class);
            verify(productRepository).findAll(any(Specification.class), pageableCaptor.capture());
            Sort sort = pageableCaptor.getValue().getSort();
            assertThat(sort.getOrderFor("createdAt")).isNotNull();
            assertThat(sort.getOrderFor("createdAt").getDirection()).isEqualTo(Sort.Direction.DESC);
        }

        @Test
        void shouldPreserveExplicitSort() {
            // given
            Sort explicitSort = Sort.by(Sort.Direction.ASC, "title");
            Page<Product> page = new PageImpl<>(List.of(), PageRequest.of(0, 20, explicitSort), 0);
            when(productRepository.findAll(any(Specification.class), any(Pageable.class)))
                    .thenReturn(page);

            // when
            productService.listProducts(null, PageRequest.of(0, 20, explicitSort));

            // then
            @SuppressWarnings("unchecked")
            ArgumentCaptor<Pageable> pageableCaptor = ArgumentCaptor.forClass(Pageable.class);
            verify(productRepository).findAll(any(Specification.class), pageableCaptor.capture());
            assertThat(pageableCaptor.getValue().getSort().getOrderFor("title")).isNotNull();
        }

        @Test
        void shouldTreatBlankStatusAsNoFilter() {
            // given
            Page<Product> page = new PageImpl<>(List.of(), PageRequest.of(0, 20, Sort.by(Sort.Direction.DESC, "createdAt")), 0);
            when(productRepository.findAll(any(Specification.class), any(Pageable.class)))
                    .thenReturn(page);

            // when
            PagedProductResponse response = productService.listProducts("  ", PageRequest.of(0, 20));

            // then
            assertThat(response).isNotNull();
        }
    }

    private static UpdateProductRequest updateRequest(String title, String handle, String status,
                                                       String description, String subtitle,
                                                       BigDecimal weight, BigDecimal height,
                                                       BigDecimal width, BigDecimal length,
                                                       String metadata, String externalId) {
        return new UpdateProductRequest(title, handle, status, description, subtitle,
                weight, height, width, length, metadata, externalId, null);
    }

    private static UpdateProductRequest titleOnlyUpdate(String title) {
        return updateRequest(title, null, null, null, null, null, null, null, null, null, null);
    }

    private static UpdateProductRequest emptyUpdate() {
        return updateRequest(null, null, null, null, null, null, null, null, null, null, null);
    }

    @Nested
    class UpdateProductSuccessCases {

        @Test
        void shouldUpdateTitle() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("Old Title", "old-title");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            UpdateProductRequest request = titleOnlyUpdate("New Title");

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.title()).isEqualTo("New Title");
            verify(productRepository).save(any(Product.class));
        }

        @Test
        void shouldUpdateHandle() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "old-handle");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.existsByHandleAndIdNot("new-handle", productId)).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            UpdateProductRequest request = updateRequest(null, "new-handle", null, null, null,
                    null, null, null, null, null, null);

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.handle()).isEqualTo("new-handle");
        }

        @Test
        void shouldUpdateStatus() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "my-product");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            UpdateProductRequest request = updateRequest(null, null, "PUBLISHED", null, null,
                    null, null, null, null, null, null);

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.status()).isEqualTo("PUBLISHED");
        }

        @Test
        void shouldUpdateMultipleFieldsAtOnce() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("Old Title", "old-handle");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.existsByHandleAndIdNot("new-handle", productId)).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            UpdateProductRequest request = updateRequest("New Title", "new-handle", "PUBLISHED",
                    "New description", "New subtitle",
                    new BigDecimal("2.5"), new BigDecimal("20.0"),
                    new BigDecimal("10.0"), new BigDecimal("5.0"),
                    "{\"updated\":true}", "EXT-002");

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.title()).isEqualTo("New Title");
            assertThat(response.handle()).isEqualTo("new-handle");
            assertThat(response.status()).isEqualTo("PUBLISHED");
            assertThat(response.description()).isEqualTo("New description");
            assertThat(response.subtitle()).isEqualTo("New subtitle");
            assertThat(response.weight()).isEqualByComparingTo(new BigDecimal("2.5"));
            assertThat(response.metadata()).isEqualTo("{\"updated\":true}");
            assertThat(response.externalId()).isEqualTo("EXT-002");
        }

        @Test
        void shouldReturnUnchangedProduct_whenNoFieldsProvided() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("Unchanged Product", "unchanged");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));

            UpdateProductRequest request = emptyUpdate();

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.title()).isEqualTo("Unchanged Product");
            assertThat(response.handle()).isEqualTo("unchanged");
            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldIgnoreNullFields() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("Original", "original");
            product.describeAs("Original description");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            UpdateProductRequest request = titleOnlyUpdate("Updated Title");

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.title()).isEqualTo("Updated Title");
            assertThat(response.description()).isEqualTo("Original description");
        }

        @Test
        void shouldHandleCaseInsensitiveStatusOnUpdate() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "my-product");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            UpdateProductRequest request = updateRequest(null, null, "published", null, null,
                    null, null, null, null, null, null);

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.status()).isEqualTo("PUBLISHED");
        }

        @Test
        void shouldUpdateDimensionsPartially() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "my-product");
            product.applyDimensions(new BigDecimal("1.0"), new BigDecimal("2.0"),
                    new BigDecimal("3.0"), new BigDecimal("4.0"));
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            UpdateProductRequest request = updateRequest(null, null, null, null, null,
                    new BigDecimal("9.9"), null, null, null, null, null);

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.weight()).isEqualByComparingTo(new BigDecimal("9.9"));
            assertThat(response.height()).isEqualByComparingTo(new BigDecimal("2.0"));
            assertThat(response.width()).isEqualByComparingTo(new BigDecimal("3.0"));
            assertThat(response.length()).isEqualByComparingTo(new BigDecimal("4.0"));
        }

        @Test
        void shouldTrimHandleOnUpdate() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "old-handle");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.existsByHandleAndIdNot("trimmed-handle", productId)).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            UpdateProductRequest request = updateRequest(null, "  trimmed-handle  ", null,
                    null, null, null, null, null, null, null, null);

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.handle()).isEqualTo("trimmed-handle");
        }
    }

    @Nested
    class UpdateProductFailureCases {

        @Test
        void shouldThrowNotFound_whenProductDoesNotExist() {
            // given
            UUID unknownId = UUID.randomUUID();
            when(productRepository.findById(unknownId)).thenReturn(Optional.empty());

            UpdateProductRequest request = titleOnlyUpdate("New Title");

            // when / then
            assertThatThrownBy(() -> productService.updateProduct(unknownId, request))
                    .isInstanceOf(ResourceNotFoundException.class)
                    .hasMessageContaining("Product")
                    .hasMessageContaining(unknownId.toString());

            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectDuplicateHandleOnUpdate() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "old-handle");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.existsByHandleAndIdNot("taken-handle", productId)).thenReturn(true);

            UpdateProductRequest request = updateRequest(null, "taken-handle", null, null, null,
                    null, null, null, null, null, null);

            // when / then
            assertThatThrownBy(() -> productService.updateProduct(productId, request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("taken-handle")
                    .hasMessageContaining("already exists");

            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectInvalidStatusOnUpdate() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "my-product");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));

            UpdateProductRequest request = updateRequest(null, null, "BOGUS", null, null,
                    null, null, null, null, null, null);

            // when / then
            assertThatThrownBy(() -> productService.updateProduct(productId, request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("Invalid product status")
                    .hasMessageContaining("BOGUS");

            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectBlankTitle() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "my-product");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));

            UpdateProductRequest request = titleOnlyUpdate("   ");

            // when / then
            assertThatThrownBy(() -> productService.updateProduct(productId, request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("title must not be blank");

            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectEmptyTitle() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("My Product", "my-product");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));

            UpdateProductRequest request = titleOnlyUpdate("");

            // when / then
            assertThatThrownBy(() -> productService.updateProduct(productId, request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("title must not be blank");

            verify(productRepository, never()).save(any());
        }
    }

    @Nested
    class CreateProductWithOptionsCases {

        @Test
        void shouldCreateProductWithOptions() {
            // given
            List<ProductOptionRequest> options = List.of(
                    new ProductOptionRequest("Size", List.of("S", "M", "L")),
                    new ProductOptionRequest("Color", List.of("Red", "Blue"))
            );
            CreateProductRequest request = new CreateProductRequest(
                    "T-Shirt", null, null, null, null,
                    null, null, null, null, null, null, options);
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.options()).hasSize(2);
            assertThat(response.options().get(0).title()).isEqualTo("Size");
            assertThat(response.options().get(0).values()).containsExactly("S", "M", "L");
            assertThat(response.options().get(1).title()).isEqualTo("Color");
            assertThat(response.options().get(1).values()).containsExactly("Red", "Blue");
        }

        @Test
        void shouldCreateProductWithNoOptions() {
            // given
            CreateProductRequest request = minimalRequest("Simple Product");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.options()).isEmpty();
        }

        @Test
        void shouldRejectDuplicateOptionTitles() {
            // given
            List<ProductOptionRequest> options = List.of(
                    new ProductOptionRequest("Size", List.of("S", "M")),
                    new ProductOptionRequest("Size", List.of("L", "XL"))
            );
            CreateProductRequest request = new CreateProductRequest(
                    "T-Shirt", null, null, null, null,
                    null, null, null, null, null, null, options);
            when(productRepository.existsByHandle(anyString())).thenReturn(false);

            // when / then
            assertThatThrownBy(() -> productService.createProduct(request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("Duplicate option title");

            verify(productRepository, never()).save(any());
        }
    }

    @Nested
    class UpdateProductOptionsCases {

        @Test
        void shouldAddOptionsToExistingProduct() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("T-Shirt", "t-shirt");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            List<ProductOptionRequest> options = List.of(
                    new ProductOptionRequest("Size", List.of("S", "M", "L"))
            );
            UpdateProductRequest request = new UpdateProductRequest(
                    null, null, null, null, null,
                    null, null, null, null, null, null, options);

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.options()).hasSize(1);
            assertThat(response.options().get(0).title()).isEqualTo("Size");
            assertThat(response.options().get(0).values()).containsExactly("S", "M", "L");
        }

        @Test
        void shouldUpdateExistingOptionValues() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("T-Shirt", "t-shirt");
            ProductOption sizeOption = product.addOption("Size");
            sizeOption.addValue("S");
            sizeOption.addValue("M");

            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            List<ProductOptionRequest> options = List.of(
                    new ProductOptionRequest("Size", List.of("L", "XL", "XXL"))
            );
            UpdateProductRequest request = new UpdateProductRequest(
                    null, null, null, null, null,
                    null, null, null, null, null, null, options);

            // when
            ProductResponse response = productService.updateProduct(productId, request);

            // then
            assertThat(response.options()).hasSize(1);
            assertThat(response.options().get(0).title()).isEqualTo("Size");
            assertThat(response.options().get(0).values()).containsExactly("L", "XL", "XXL");
        }

        @Test
        void shouldSoftDeleteRemovedOptions() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("T-Shirt", "t-shirt");
            product.addOption("Size").addValue("S");
            product.addOption("Color").addValue("Red");

            when(productRepository.findById(productId)).thenReturn(Optional.of(product));
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // Update with only Size — Color should be soft-deleted
            List<ProductOptionRequest> options = List.of(
                    new ProductOptionRequest("Size", List.of("S", "M"))
            );
            UpdateProductRequest request = new UpdateProductRequest(
                    null, null, null, null, null,
                    null, null, null, null, null, null, options);

            // when
            productService.updateProduct(productId, request);

            // then — Color option should be soft-deleted
            assertThat(product.getOptions())
                    .filteredOn(o -> "Color".equals(o.getTitle()))
                    .allSatisfy(o -> assertThat(o.getDeletedAt()).isNotNull());
        }

        @Test
        void shouldNotModifyOptionsWhenOptionsFieldIsNull() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("T-Shirt", "t-shirt");
            product.addOption("Size").addValue("S");

            when(productRepository.findById(productId)).thenReturn(Optional.of(product));

            UpdateProductRequest request = new UpdateProductRequest(
                    null, null, null, null, null,
                    null, null, null, null, null, null, null);

            // when
            productService.updateProduct(productId, request);

            // then — options should remain untouched, no save
            assertThat(product.getOptions()).hasSize(1);
            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectDuplicateOptionTitlesOnUpdate() {
            // given
            UUID productId = UUID.randomUUID();
            Product product = Product.create("T-Shirt", "t-shirt");
            when(productRepository.findById(productId)).thenReturn(Optional.of(product));

            List<ProductOptionRequest> options = List.of(
                    new ProductOptionRequest("Color", List.of("Red")),
                    new ProductOptionRequest("Color", List.of("Blue"))
            );
            UpdateProductRequest request = new UpdateProductRequest(
                    null, null, null, null, null,
                    null, null, null, null, null, null, options);

            // when / then
            assertThatThrownBy(() -> productService.updateProduct(productId, request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("Duplicate option title");

            verify(productRepository, never()).save(any());
        }
    }
}
