package com.inventory.demo.product.service;

import com.inventory.demo.exception.BusinessRuleException;
import com.inventory.demo.product.api.CreateProductRequest;
import com.inventory.demo.product.api.ProductResponse;
import com.inventory.demo.product.domain.Product;
import com.inventory.demo.product.repository.ProductRepository;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class ProductServiceTest {

    @Mock
    private ProductRepository productRepository;

    @InjectMocks
    private ProductService productService;

    private static CreateProductRequest minimalRequest(String title) {
        return new CreateProductRequest(title, null, null, null, null,
                null, null, null, null, null, null);
    }

    private static CreateProductRequest requestWithHandle(String title, String handle) {
        return new CreateProductRequest(title, handle, null, null, null,
                null, null, null, null, null, null);
    }

    private static CreateProductRequest requestWithStatus(String title, String status) {
        return new CreateProductRequest(title, null, status, null, null,
                null, null, null, null, null, null);
    }

    private static CreateProductRequest fullRequest() {
        return new CreateProductRequest(
                "Premium Widget",
                "premium-widget",
                "PUBLISHED",
                "A premium widget description",
                "The best widget",
                new BigDecimal("1.5"),
                new BigDecimal("10.0"),
                new BigDecimal("5.0"),
                new BigDecimal("3.0"),
                "{\"color\":\"red\"}",
                "EXT-001"
        );
    }

    @Nested
    class SuccessCases {

        @Test
        void shouldCreateProductWithAutoGeneratedHandle() {
            // given
            CreateProductRequest request = minimalRequest("My Cool Product");
            when(productRepository.existsByHandle("my-cool-product")).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.title()).isEqualTo("My Cool Product");
            assertThat(response.handle()).isEqualTo("my-cool-product");
            assertThat(response.status()).isEqualTo("DRAFT");
        }

        @Test
        void shouldCreateProductWithExplicitHandle() {
            // given
            CreateProductRequest request = requestWithHandle("My Product", "custom-handle");
            when(productRepository.existsByHandle("custom-handle")).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.handle()).isEqualTo("custom-handle");
        }

        @Test
        void shouldDefaultToDraftStatus() {
            // given
            CreateProductRequest request = minimalRequest("Test Product");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.status()).isEqualTo("DRAFT");
        }

        @Test
        void shouldApplyExplicitStatus() {
            // given
            CreateProductRequest request = requestWithStatus("Test Product", "PUBLISHED");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.status()).isEqualTo("PUBLISHED");
        }

        @Test
        void shouldApplyAllOptionalFields() {
            // given
            CreateProductRequest request = fullRequest();
            when(productRepository.existsByHandle("premium-widget")).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.title()).isEqualTo("Premium Widget");
            assertThat(response.handle()).isEqualTo("premium-widget");
            assertThat(response.status()).isEqualTo("PUBLISHED");
            assertThat(response.description()).isEqualTo("A premium widget description");
            assertThat(response.subtitle()).isEqualTo("The best widget");
            assertThat(response.weight()).isEqualByComparingTo(new BigDecimal("1.5"));
            assertThat(response.height()).isEqualByComparingTo(new BigDecimal("10.0"));
            assertThat(response.width()).isEqualByComparingTo(new BigDecimal("5.0"));
            assertThat(response.length()).isEqualByComparingTo(new BigDecimal("3.0"));
            assertThat(response.metadata()).isEqualTo("{\"color\":\"red\"}");
            assertThat(response.externalId()).isEqualTo("EXT-001");
        }

        @Test
        void shouldSaveProductToRepository() {
            // given
            CreateProductRequest request = minimalRequest("Save Test");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            productService.createProduct(request);

            // then
            ArgumentCaptor<Product> captor = ArgumentCaptor.forClass(Product.class);
            verify(productRepository).save(captor.capture());
            assertThat(captor.getValue().getTitle()).isEqualTo("Save Test");
        }

        @Test
        void shouldHandleCaseInsensitiveStatusInput() {
            // given
            CreateProductRequest request = requestWithStatus("Test Product", "published");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);
            when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

            // when
            ProductResponse response = productService.createProduct(request);

            // then
            assertThat(response.status()).isEqualTo("PUBLISHED");
        }
    }

    @Nested
    class FailureCases {

        @Test
        void shouldRejectDuplicateHandle() {
            // given
            CreateProductRequest request = requestWithHandle("My Product", "existing-handle");
            when(productRepository.existsByHandle("existing-handle")).thenReturn(true);

            // when / then
            assertThatThrownBy(() -> productService.createProduct(request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("existing-handle")
                    .hasMessageContaining("already exists");

            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectDuplicateAutoGeneratedHandle() {
            // given
            CreateProductRequest request = minimalRequest("Existing Product");
            when(productRepository.existsByHandle("existing-product")).thenReturn(true);

            // when / then
            assertThatThrownBy(() -> productService.createProduct(request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("existing-product");

            verify(productRepository, never()).save(any());
        }

        @Test
        void shouldRejectInvalidStatus() {
            // given
            CreateProductRequest request = requestWithStatus("Test Product", "INVALID_STATUS");
            when(productRepository.existsByHandle(anyString())).thenReturn(false);

            // when / then
            assertThatThrownBy(() -> productService.createProduct(request))
                    .isInstanceOf(BusinessRuleException.class)
                    .hasMessageContaining("Invalid product status")
                    .hasMessageContaining("INVALID_STATUS");

            verify(productRepository, never()).save(any());
        }
    }

    @Nested
    class SlugGenerationCases {

        @Test
        void shouldConvertTitleToLowercaseSlug() {
            assertThat(productService.generateSlug("My Cool Product"))
                    .isEqualTo("my-cool-product");
        }

        @Test
        void shouldReplaceSpecialCharacters() {
            assertThat(productService.generateSlug("Product @ 50% Off!"))
                    .isEqualTo("product-50-off");
        }

        @Test
        void shouldCollapseConsecutiveHyphens() {
            assertThat(productService.generateSlug("Product -- Extra"))
                    .isEqualTo("product-extra");
        }

        @Test
        void shouldTrimLeadingAndTrailingHyphens() {
            assertThat(productService.generateSlug(" --Product-- "))
                    .isEqualTo("product");
        }

        @Test
        void shouldHandleMultipleSpaces() {
            assertThat(productService.generateSlug("Product   With   Spaces"))
                    .isEqualTo("product-with-spaces");
        }
    }
}
